export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ARCHDIOCESE_ADMIN = 'ARCHDIOCESE_ADMIN',
  PARISH_ADMIN = 'PARISH_ADMIN',
  COUPLE_COORDINATOR = 'COUPLE_COORDINATOR',
  MEMBER = 'MEMBER',
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
